# Generated by Django 5.2.18 on 2026-10-09 14:35

import portfolio.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, storage=portfolio.storage.raw_storage, upload_to='cv/', verbose_name='CV (PDF)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, storage=portfolio.storage.image_storage, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, storage=portfolio.storage.image_storage, upload_to='projects/covers/'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(storage=portfolio.storage.raw_storage, upload_to='projects/documents/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(storage=portfolio.storage.image_storage, upload_to='projects/gallery/'),
        ),
    ]
